#######################################################################################
# project: Juniper
# prototype: juniper_canopy
# author: Paul Calnon
# created-on: 2025-12-06
# created-by: conda 25.11.0
# platform: linux-64
# python: 3.14
#######################################################################################
# This file may be used to create the Juniper Canopy environment
#     with conda and miniforge3 using:
# create env: $ conda create --name <env> --file <file>
#                 e.g. $ conda create --name JuniperCanopy --file juniper_canopy/conf/conda_environment.yaml
# generate the dependencies section
# generate file:  $ conda list -e >> <this file: juniper_canopy/conf/conda_environment.yaml>
#######################################################################################
name: JuniperCanopy
channels:
  - conda-forge
  - pytorch
  - nvidia
  - plotly
  - RMG
  - numba
  - jasonb857
  - ehmoussi
  - konstantin-orangeqs
dependencies:
  #  - python=3.11
  #  - python=3.12
  #  - python=3.13
  - python=3.14.0=h32b2ec7_103_cp314
  # - python=3.14
  # add other dependencies
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - a2wsgi=1.10.10=pyhcf101f3_1
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - backports.asyncio.runner=1.2.0=pyh5ded981_2
  - backports.zstd=1.1.0=py314h680f03e_1
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py314h3de4e8d_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py314h4a8dc5f_1
  - cfgv=3.5.0=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - coverage=7.12.0=py314h67df5f8_0
  - dash=3.3.0=pyhd8ed1ab_0
  # - dash-bootstrap-components=2.0.4=pypi_0
  # - dash-bootstrap-components=2.0.4=py314h67df5f8_0
  # - dash-bootstrap-components=2.0.4=conda_forge
  - dash-bootstrap-components=2.0.4
  # - dash-bootstrap-components
  - distlib=0.4.0=pyhd8ed1ab_0
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fastapi=0.123.9=h9db8b3a_0
  - fastapi-cli=0.0.16=pyhcf101f3_1
  - fastapi-core=0.123.9=pyhcf101f3_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  # - fsspec=2025.12.0=pypi_0
  - fsspec=2025.12.0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py314h5bd0f2a_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - identify=2.6.15=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libcblas=3.11.0=4_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_15
  - libgfortran=15.2.0=h69a702a_15
  - libgfortran5=15.2.0=h68bc16d_15
  - libgomp=15.2.0=he0feb66_15
  - liblapack=3.11.0=4_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_15
  - libuuid=2.41.2=h5347b49_1
  - libuv=1.51.0=hb03c661_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  # - mpmath=1.3.0=pypi_0
  - mpmath=1.3.0
  - narwhals=2.13.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6=pyhcf101f3_0
  - nodeenv=1.9.1=pyhd8ed1ab_1
  - numpy=2.3.5=py314h2b28147_0
  # - nvidia-cublas-cu12=12.8.4.1=pypi_0
  # - nvidia-cublas-cu12=12.8.4.1
  # - nvidia-cublas-cu12
  # - nvidia-cuda-cupti-cu12=12.8.90=pypi_0
  - nvidia-cuda-cupti-cu12=12.8.90
  # - nvidia-cuda-nvrtc-cu12=12.8.93=pypi_0
  - nvidia-cuda-nvrtc-cu12=12.8.93
  # - nvidia-cuda-runtime-cu12=12.8.90=pypi_0
  - nvidia-cuda-runtime-cu12=12.8.90
  # - nvidia-cudnn-cu12=9.10.2.21=pypi_0
  - nvidia-cudnn-cu12=9.10.2.21
  # - nvidia-cufft-cu12=11.3.3.83=pypi_0
  - nvidia-cufft-cu12=11.3.3.83
  # - nvidia-cufile-cu12=1.13.1.3=pypi_0
  - nvidia-cufile-cu12=1.13.1.3
  # - nvidia-curand-cu12=10.3.9.90=pypi_0
  - nvidia-curand-cu12=10.3.9.90
  # - nvidia-cusolver-cu12=11.7.3.90=pypi_0
  - nvidia-cusolver-cu12=11.7.3.90
  # - nvidia-cusparse-cu12=12.5.8.93=pypi_0
  - nvidia-cusparse-cu12=12.5.8.93
  # - nvidia-cusparselt-cu12=0.7.1=pypi_0
  - nvidia-cusparselt-cu12=0.7.1
  # - nvidia-nccl-cu12=2.27.5=pypi_0
  - nvidia-nccl-cu12=2.27.5
  # - nvidia-nvjitlink-cu12=12.8.93=pypi_0
  - nvidia-nvjitlink-cu12=12.8.93
  # - nvidia-nvshmem-cu12=3.3.20=pypi_0
  - nvidia-nvshmem-cu12=3.3.20
  # - nvidia-nvtx-cu12=12.8.90=pypi_0
  - nvidia-nvtx-cu12=12.8.90
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.3=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhf9edf01_1
  - pre-commit=4.5.0=pyha770c72_0
  - psutil=7.1.3=py314h0f05182_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py314h2e6c369_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.1=pyhcf101f3_0
  - pytest-asyncio=1.3.0=pyhcf101f3_0
  - pytest-cov=7.0.0=pyhcf101f3_1
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python_abi=3.14=8_cp314
  - pyyaml=6.0.3=pyh7db6752_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - retrying=1.4.2=pyhe01879c_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.17.0=pyhcf101f3_0
  - scipy=1.16.3=py314he7377e1_1
  # - setuptools=80.9.0=pypi_0
  - setuptools=80.9.0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - sniffio=1.3.1=pyhd8ed1ab_2
  - starlette=0.50.0=pyhfdc7a7d_0
  # - sympy=1.14.0=pypi_0
  - sympy=1.14.0
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.3.0=pyhcf101f3_0
  # - torch=2.9.1=pypi_0
  - torch=2.9.1
  # - triton=3.5.1=pypi_0
  - triton=3.5.1
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ukkonen=1.0.1=py314h9891dd4_6
  - urllib3=2.6.0=pyhd8ed1ab_0
  - uvicorn=0.38.0=pyh31011fe_0
  - uvicorn-standard=0.38.0=h31011fe_0
  - uvloop=0.22.1=py314h5bd0f2a_1
  - virtualenv=20.35.4=pyhd8ed1ab_0
  - watchfiles=1.1.1=py314ha5689aa_0
  - websockets=15.0.1=py314h31f8a6b_2
  - werkzeug=3.1.4=pyhcf101f3_0
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=hb78ec9c_6
