#####################################################################################################################################################################################################
# Project:       Juniper
# Sub-Project:   JuniperCanopy
# Application:   juniper_canopy
# Purpose:       Monitoring and Diagnostic Frontend for Cascade Correlation Neural Network
#
# Author:        Paul Calnon
# Version:       1.0.0
# Script Name:   setup-miniconda-patched-conda_environment.yaml
# Script Path:   <Project>/<Sub-Project>/<Application>/conf/
#
# Date:          2025-12-06
# Last Modified: 2026-01-21
#
# License:       MIT License
# Copyright:     Copyright (c) 2024,2025,2026 Paul Calnon
#
# Description:
#     This script pulls together a report on the source files in the current Application.
#
#####################################################################################################################################################################################################
# Notes:
#     created-by: conda 25.11.0
#     platform: linux-64
#     python: 3.14
#
#     Longest File(s):  (1999 lines) --  NeuralNetwork.py
#     Methods File(s):  (76 methods) --  EvolveState.py
#     Largest File(s):  (108 KB)     --  NeuralNetwork.py
#     Roughest File(s): (24 TODOs)   --  DNA.py
#
#####################################################################################################################################################################################################
# References:
#
#     This file may be used to create the Juniper Canopy environment
#         with conda and miniforge3 using:
#     create env: conda create --name <env> --file <file>
#         e.g., $ conda create --name JuniperCanopy --file juniper_canopy/conf/conda_environment.yaml
#     Update env: conda env update --name <env> --file <file>
#         e.g., $ conda env update --name JuniperCanopy --file juniper_canopy/conf/conda_environment.yaml
#     Generate deps: conda list --explicit > <file>
#         e.g., $ conda list -e >> juniper_canopy/conf/conda_environment.yaml
#
#####################################################################################################################################################################################################
# TODO :
#     1. Add parent project dir
#
#####################################################################################################################################################################################################
# COMPLETED:
#
#####################################################################################################################################################################################################
name: JuniperCanopy
channels:
  - conda-forge
  - pytorch
  - nvidia
  - plotly
  - RMG
  - numba
  - jasonb857
  - ehmoussi
  - konstantin-orangeqs
dependencies:
  - python-3.14.2-h32b2ec7_100_cp314.conda

  # Add other dependencies
  - shellcheck-0.10.0-ha770c72_0.conda
  - _libgcc_mutex-0.1-conda_forge.tar.bz2
  - ca-certificates-2025.11.12-hbd8a1cb_0.conda
  - cuda-version-13.1-h2ff5cdb_3.conda
  - font-ttf-dejavu-sans-mono-2.37-hab24e00_0.tar.bz2
  - font-ttf-inconsolata-3.000-h77eed37_0.tar.bz2
  - font-ttf-source-code-pro-2.038-h77eed37_0.tar.bz2
  - font-ttf-ubuntu-0.83-h77eed37_3.conda
  - kernel-headers_linux-64-6.12.0-he073ed8_3.conda
  - libgcc-devel_linux-64-14.3.0-hf649bbc_115.conda
  - libglvnd-1.7.0-ha4b6fd6_2.conda
  - libgomp-15.2.0-he0feb66_15.conda
  - libstdcxx-devel_linux-64-14.3.0-h9f08a49_115.conda
  - python_abi-3.14-8_cp314.conda
  - tzdata-2025b-h78e105d_0.conda
  - _openmp_mutex-4.5-2_gnu.tar.bz2
  - cuda-cccl_linux-64-13.1.78-ha770c72_0.conda
  - cuda-crt-dev_linux-64-13.1.80-ha770c72_0.conda
  - cuda-crt-tools-13.1.80-ha770c72_0.conda
  - cuda-cudart-static_linux-64-13.1.80-h376f20c_0.conda
  - cuda-cudart_linux-64-13.1.80-h376f20c_0.conda
  - cuda-driver-dev_linux-64-13.1.80-h376f20c_0.conda
  - cuda-nsight-13.1.68-h7938cbb_0.conda
  - cuda-nvvm-dev_linux-64-13.1.80-ha770c72_0.conda
  - fonts-conda-forge-1-hc364b38_1.conda
  - libnvptxcompiler-dev_linux-64-13.1.80-ha770c72_0.conda
  - libopengl-1.7.0-ha4b6fd6_2.conda
  - sysroot_linux-64-2.39-hc4b9eeb_3.conda
  - cuda-cudart-dev_linux-64-13.1.80-h376f20c_0.conda
  - fonts-conda-ecosystem-1-0.tar.bz2
  - libgcc-15.2.0-he0feb66_15.conda
  - libnvptxcompiler-dev-13.1.80-ha770c72_0.conda
  - alsa-lib-1.2.14-hb9d3cd8_0.conda
  - attr-2.5.2-h39aace5_0.conda
  - bzip2-1.0.8-hda65f42_8.conda
  - cuda-nvcc-dev_linux-64-13.1.80-he91c749_0.conda
  - cuda-nvvm-impl-13.1.80-h4bc722e_0.conda
  - cuda-nvvm-tools-13.1.80-h4bc722e_0.conda
  - keyutils-1.6.3-hb9d3cd8_0.conda
  - libexpat-2.7.3-hecca717_0.conda
  - libffi-3.5.2-h9ec8514_0.conda
  - libgcc-ng-15.2.0-h69a702a_15.conda
  - libgfortran5-15.2.0-h68bc16d_15.conda
  - libiconv-1.18-h3b78370_2.conda
  - liblzma-5.8.1-hb9d3cd8_2.conda
  - libmpdec-4.0.0-hb9d3cd8_0.conda
  - libnl-3.11.0-hb9d3cd8_0.conda
  - libnuma-2.0.18-hb9d3cd8_3.conda
  - libstdcxx-15.2.0-h934c35e_15.conda
  - libuuid-2.41.2-h5347b49_1.conda
  - libuv-1.51.0-hb03c661_1.conda
  - libzlib-1.3.1-hb9d3cd8_2.conda
  - ncurses-6.5-h2d0b736_3.conda
  - openssl-3.6.0-h26f9b46_0.conda
  - pthread-stubs-0.4-hb9d3cd8_1002.conda
  - xorg-libice-1.1.2-hb9d3cd8_0.conda
  - xorg-libxau-1.0.12-hb03c661_1.conda
  - xorg-libxdmcp-1.1.5-hb03c661_1.conda
  - yaml-0.2.5-h280c20c_3.conda
  - cuda-ctadvisor-13.1.80-h676940d_0.conda
  - cuda-cudart-13.1.80-hecca717_0.conda
  - cuda-cudart-static-13.1.80-hecca717_0.conda
  - cuda-cupti-13.1.75-h676940d_0.conda
  - cuda-cuxxfilt-13.1.80-hffce074_0.conda
  - cuda-driver-dev-13.1.80-hecca717_0.conda
  - cuda-nvcc-tools-13.1.80-he02047a_0.conda
  - cuda-nvdisasm-13.1.80-hffce074_0.conda
  - cuda-nvml-dev-13.1.68-hffce074_0.conda
  - cuda-nvprune-13.1.80-hffce074_0.conda
  - cuda-nvrtc-13.1.80-hecca717_0.conda
  - cuda-nvtx-13.1.68-hecca717_0.conda
  - cuda-sanitizer-api-13.1.75-h10ca0ad_0.conda
  - cuda-tileiras-13.1.80-hecca717_1.conda
  - libcap-2.77-h3ff7636_0.conda
  - libcufft-12.1.0.31-hecca717_0.conda
  - libcurand-10.4.1.34-h676940d_0.conda
  - libedit-3.1.20250104-pl5321h7949ede_0.conda
  - libgfortran-15.2.0-h69a702a_15.conda
  - libnpp-13.0.2.21-h676940d_0.conda
  - libnvfatbin-13.1.80-hecca717_0.conda
  - libnvjitlink-13.1.80-hecca717_0.conda
  - libnvjpeg-13.0.2.28-hecca717_0.conda
  - libpng-1.6.53-h421ea60_0.conda
  - libsanitizer-14.3.0-h8f1669f_15.conda
  - libsqlite-3.51.1-h0c1763c_0.conda
  - libstdcxx-ng-15.2.0-hdf11a46_15.conda
  - libxcb-1.17.0-h8a09558_0.conda
  - libxkbfile-1.1.0-h166bdaf_1.conda
  - nspr-4.38-h29cc59b_0.conda
  - opencl-headers-2025.06.13-h5888daf_0.conda
  - pcre2-10.47-haa7fec5_0.conda
  - readline-8.2-h8c095d6_2.conda
  - tk-8.6.13-noxft_ha0e22de_103.conda
  - wayland-1.24.0-hd6090a7_1.conda
  - xorg-libsm-1.2.6-he73a12e_0.conda
  - zstd-1.5.7-hb78ec9c_6.conda
  - cuda-cudart-dev-13.1.80-hecca717_0.conda
  - cuda-cuobjdump-13.1.80-hffce074_0.conda
  - cuda-cupti-dev-13.1.75-h676940d_0.conda
  - cuda-nvrtc-dev-13.1.80-hecca717_0.conda
  - gmp-6.3.0-hac33072_2.conda
  - icu-75.1-he02047a_0.conda
  - krb5-1.21.3-h659f571_0.conda
  - ld_impl_linux-64-2.45-default_hbd61a6d_104.conda
  - libcublas-13.2.0.9-h676940d_0.conda
  - libcufft-dev-12.1.0.31-hecca717_0.conda
  - libcurand-dev-10.4.1.34-h676940d_0.conda
  - libcusparse-12.7.2.19-hecca717_0.conda
  - libfreetype6-2.14.1-h73754d4_0.conda
  - libglib-2.86.2-h6548e54_1.conda
  - libnpp-dev-13.0.2.21-h676940d_0.conda
  - libnvfatbin-dev-13.1.80-hecca717_0.conda
  - libnvjitlink-dev-13.1.80-hecca717_0.conda
  - libopenblas-0.3.30-pthreads_h94d23a6_4.conda
  - libsystemd0-258.2-h6569c3e_1.conda
  - libudev1-258.2-h6569c3e_1.conda
  - nss-3.118-h445c969_0.conda
  - ocl-icd-2.3.3-hb9d3cd8_0.conda
  - xcb-util-0.4.1-h4f16b4b_2.conda
  - xcb-util-keysyms-0.4.1-hb711507_0.conda
  - xcb-util-renderutil-0.3.10-hb711507_0.conda
  - xcb-util-wm-0.4.2-hb711507_0.conda
  - xorg-libx11-1.8.12-h4f16b4b_0.conda
  - binutils_impl_linux-64-2.45-default_hfdba357_104.conda
  - cuda-gdb-13.1.68-h1b59fc5_0.conda
  - cuda-nvcc-impl-13.1.80-h85509e4_0.conda
  - cuda-opencl-13.1.80-hecca717_0.conda
  - cuda-profiler-api-13.1.80-h7938cbb_0.conda
  - dbus-1.16.2-h24cb091_1.conda
  - libblas-3.11.0-4_h4a7cf45_openblas.conda
  - libcublas-dev-13.2.0.9-h676940d_0.conda
  - libcusolver-12.0.7.41-h676940d_0.conda
  - libcusparse-dev-12.7.2.19-hecca717_0.conda
  - libfreetype-2.14.1-ha770c72_0.conda
  - libnvjpeg-dev-13.0.2.28-ha770c72_0.conda
  - libxml2-16-2.15.1-ha9997c6_0.conda
  - mpfr-4.2.1-h90cbb55_3.conda
  - nodejs-24.9.0-heeeca48_0.conda
  - rdma-core-60.0-hecca717_0.conda
  - xcb-util-image-0.4.0-hb711507_2.conda
  - xkeyboard-config-2.46-hb03c661_0.conda
  - xorg-libxext-1.3.6-hb9d3cd8_0.conda
  - xorg-libxfixes-6.0.2-hb03c661_0.conda
  - xorg-libxrender-0.9.12-hb9d3cd8_0.conda
  - xorg-libxt-1.3.1-hb9d3cd8_0.conda
  - annotated-doc-0.0.4-pyhcf101f3_0.conda
  - astor-0.8.1-pyhd8ed1ab_1.conda
  - attrs-25.4.0-pyhcf101f3_1.conda
  - backports.asyncio.runner-1.2.0-pyh5ded981_2.conda
  - backports.zstd-1.1.0-py314h680f03e_1.conda
  - binutils-2.45-default_h4852527_104.conda
  - binutils_linux-64-2.45-default_h4852527_104.conda
  - blinker-1.9.0-pyhff2d567_0.conda
  - brotli-python-1.2.0-py314h3de4e8d_1.conda
  - certifi-2025.11.12-pyhd8ed1ab_0.conda
  - cfgv-3.5.0-pyhd8ed1ab_0.conda
  - charset-normalizer-3.4.4-pyhd8ed1ab_0.conda
  - click-8.3.1-pyh8f84b5b_1.conda
  - colorama-0.4.6-pyhd8ed1ab_1.conda
  - cpython-3.14.2-py314hd8ed1ab_100.conda
  - cuda-command-line-tools-13.1.0-ha770c72_0.conda
  - cuda-nvcc_linux-64-13.1.80-hb2fc203_0.conda
  - cuda-opencl-dev-13.1.80-hecca717_0.conda
  - distlib-0.4.0-pyhd8ed1ab_0.conda
  - distro-1.9.0-pyhd8ed1ab_1.conda
  - filelock-3.20.2-pyhd8ed1ab_0.conda
  - freetype-2.14.1-ha770c72_0.conda
  - gcc_impl_linux-64-14.3.0-h319ec69_15.conda
  - hpack-4.1.0-pyhd8ed1ab_0.conda
  - httptools-0.7.1-py314h5bd0f2a_1.conda
  - hyperframe-6.1.0-pyhd8ed1ab_0.conda
  - idna-3.11-pyhd8ed1ab_0.conda
  - iniconfig-2.3.0-pyhd8ed1ab_0.conda
  - itsdangerous-2.2.0-pyhd8ed1ab_1.conda
  - libcblas-3.11.0-4_h0358290_openblas.conda
  - libcufile-1.16.0.49-hd07211c_0.conda
  - libcusolver-dev-12.0.7.41-h676940d_0.conda
  - liblapack-3.11.0-4_h47877c9_openblas.conda
  - libxml2-2.15.1-h26afc86_0.conda
  - markupsafe-3.0.3-pyh7db6752_0.conda
  - mccabe-0.7.0-pyhd8ed1ab_1.conda
  - mdurl-0.1.2-pyhd8ed1ab_1.conda
  - mpc-1.3.1-h24ddda3_1.conda
  - mpmath-1.3.0-pyhd8ed1ab_1.conda
  - narwhals-2.13.0-pyhcf101f3_0.conda
  - nest-asyncio-1.6.0-pyhd8ed1ab_1.conda
  - networkx-3.6-pyhcf101f3_0.conda
  - packaging-25.0-pyh29332c3_1.conda
  - pathspec-0.12.1-pyhd8ed1ab_1.conda
  - pip-25.3-pyh145f28c_0.conda
  - platformdirs-4.5.1-pyhcf101f3_0.conda
  - pluggy-1.6.0-pyhf9edf01_1.conda
  - prettier-3.7.4-h7e4c9f4_0.conda
  - psutil-7.1.3-py314h0f05182_0.conda
  - pycodestyle-2.14.0-pyhd8ed1ab_0.conda
  - pycparser-2.22-pyh29332c3_1.conda
  - pyflakes-3.4.0-pyhd8ed1ab_0.conda
  - pygments-2.19.2-pyhd8ed1ab_0.conda
  - pysocks-1.7.1-pyha55dd90_7.conda
  - python-dotenv-1.2.1-pyhcf101f3_0.conda
  - python-multipart-0.0.20-pyhff2d567_0.conda
  - pyyaml-6.0.3-pyh7db6752_0.conda
  - retrying-1.4.2-pyhe01879c_0.conda
  - setuptools-80.9.0-pyhff2d567_0.conda
  - shellingham-1.5.4-pyhd8ed1ab_2.conda
  - sniffio-1.3.1-pyhd8ed1ab_2.conda
  - toml-0.10.2-pyhcf101f3_3.conda
  - tomli-2.3.0-pyhcf101f3_0.conda
  - typing_extensions-4.15.0-pyhcf101f3_0.conda
  - uvloop-0.22.1-py314h5bd0f2a_1.conda
  - websockets-15.0.1-py314h31f8a6b_2.conda
  - xcb-util-cursor-0.1.6-hb03c661_0.conda
  - xorg-libxcomposite-0.4.6-hb9d3cd8_2.conda
  - xorg-libxdamage-1.1.6-hb9d3cd8_0.conda
  - xorg-libxi-1.8.2-hb9d3cd8_0.conda
  - xorg-libxmu-1.2.1-hb9d3cd8_1.conda
  - xorg-libxrandr-1.5.4-hb9d3cd8_0.conda
  - zipp-3.23.0-pyhcf101f3_1.conda
  - a2wsgi-1.10.10-pyhcf101f3_1.conda
  - cffi-2.0.0-py314h4a8dc5f_1.conda
  - conda-gcc-specs-14.3.0-he8ccf15_15.conda
  - coverage-7.12.0-py314h67df5f8_0.conda
  - cuda-libraries-13.1.0-ha770c72_0.conda
  - dnspython-2.8.0-pyhcf101f3_0.conda
  - exceptiongroup-1.3.1-pyhd8ed1ab_0.conda
  - flake8-7.3.0-pyhd8ed1ab_0.conda
  - fontconfig-2.15.0-h7e30c49_1.conda
  - gcc_linux-64-14.3.0-h298d278_14.conda
  - gds-tools-1.16.0.49-h676940d_0.conda
  - gmpy2-2.2.1-py314h28848ee_2.conda
  - gxx_impl_linux-64-14.3.0-h2185e75_15.conda
  - h11-0.16.0-pyhd8ed1ab_0.conda
  - h2-4.3.0-pyhcf101f3_0.conda
  - importlib-metadata-8.7.0-pyhe01879c_1.conda
  - jinja2-3.1.6-pyhcf101f3_1.conda
  - libcufile-dev-1.16.0.49-h676940d_0.conda
  - libxkbcommon-1.13.1-hca5e8e5_0.conda
  - maison-2.0.0-pyhcf101f3_2.conda
  - markdown-it-py-4.0.0-pyhd8ed1ab_0.conda
  - nodeenv-1.9.1-pyhd8ed1ab_1.conda
  - numpy-2.3.5-py314h2b28147_0.conda
  - plotly-6.5.0-pyhd8ed1ab_0.conda
  - ruyaml-0.91.0-pyhd8ed1ab_1.conda
  - typer-slim-0.20.0-pyhcf101f3_1.conda
  - typing-extensions-4.15.0-h396c80c_0.conda
  - typing-inspection-0.4.2-pyhd8ed1ab_1.conda
  - virtualenv-20.35.4-pyhd8ed1ab_0.conda
  - werkzeug-3.1.4-pyhcf101f3_0.conda
  - xclip-0.13-hb9d3cd8_4.conda
  - xorg-libxtst-1.2.5-hb9d3cd8_3.conda
  - yamllint-1.37.1-pyhe01879c_0.conda
  - annotated-types-0.7.0-pyhd8ed1ab_1.conda
  - anyio-4.12.0-pyhcf101f3_0.conda
  - cuda-libraries-dev-13.1.0-ha770c72_0.conda
  - cuda-runtime-13.1.0-ha804496_0.conda
  - email-validator-2.3.0-pyhd8ed1ab_0.conda
  - flake8-bugbear-25.11.29-pyhd8ed1ab_0.conda
  - flake8-comprehensions-3.17.0-pyhd8ed1ab_0.conda
  - flake8-simplify-0.22.0-pyhd8ed1ab_0.conda
  - flask-3.1.2-pyhd8ed1ab_0.conda
  - gcc-14.3.0-h0dff253_15.conda
  - gxx_linux-64-14.3.0-hcfe7c2f_14.conda
  - nsight-compute-2025.4.0.12-h6a507f3_0.conda
  - pydantic-core-2.41.5-py314h2e6c369_1.conda
  - pytest-9.0.1-pyhcf101f3_0.conda
  - rich-14.2.0-pyhcf101f3_0.conda
  - scipy-1.16.3-py314he7377e1_1.conda
  - sympy-1.14.0-pyh2585a3b_105.conda
  - ukkonen-1.0.1-py314h9891dd4_6.conda
  - urllib3-2.6.3-pyhd8ed1ab_0.conda
  - uvicorn-0.38.0-pyh31011fe_0.conda
  - c-compiler-1.11.0-h4d9bdce_0.conda
  - cuda-nvcc-13.1.80-hcdd1206_0.conda
  - cuda-visual-tools-13.1.0-ha770c72_0.conda
  - email_validator-2.3.0-hd8ed1ab_0.conda
  - gxx-14.3.0-h76987e4_15.conda
  - httpcore-1.0.9-pyh29332c3_0.conda
  - identify-2.6.15-pyhd8ed1ab_0.conda
  - pydantic-2.12.5-pyhcf101f3_1.conda
  - pytest-asyncio-1.3.0-pyhcf101f3_0.conda
  - pytest-cov-7.0.0-pyhcf101f3_1.conda
  - pytest-metadata-3.1.1-pyhd8ed1ab_1.conda
  - requests-2.32.5-pyhd8ed1ab_0.conda
  - rich-toolkit-0.17.0-pyhcf101f3_0.conda
  - starlette-0.50.0-pyhfdc7a7d_0.conda
  - typer-slim-standard-0.20.0-h4daf872_1.conda
  - watchfiles-1.1.1-py314ha5689aa_0.conda
  - cuda-tools-13.1.0-ha770c72_0.conda
  - cxx-compiler-1.11.0-hfcd1e18_0.conda
  - dash-3.3.0-pyhd8ed1ab_0.conda
  - fastapi-core-0.123.9-pyhcf101f3_0.conda
  - httpx-0.28.1-pyhd8ed1ab_0.conda
  - pre-commit-4.5.0-pyha770c72_0.conda
  - pytest-html-4.1.1-pyhd8ed1ab_1.conda
  - typer-0.20.0-pyhefaf540_1.conda
  - uvicorn-standard-0.38.0-h31011fe_0.conda
  - yamlfix-1.19.0-pyhd8ed1ab_0.conda
  - cuda-compiler-13.1.0-hbad6d8a_0.conda
  - dash-bootstrap-components-2.0.4-pyhcf101f3_0.conda
  - fastapi-cli-0.0.16-pyhcf101f3_1.conda
  - cuda-toolkit-13.1.0-ha804496_0.conda
  - fastapi-0.123.9-h9db8b3a_0.conda
  - cuda-13.1.0-ha804496_0.conda
