---
version: 1
formatters:
  formatter_console:
    format: "[%(filename)s:%(lineno)d] (%(asctime)s) [%(levelname)s] %(message)s"
    datefmt: "%y-%m-%d %H:%M:%S"
  formatter_file:
    format: "[%(filename)s: %(funcName)s:%(lineno)d] (%(asctime)s) [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  handler_console:
    class: logging.StreamHandler
    level: INFO
    formatter: formatter_console
    stream: ext://sys.stdout
  handler_file:
    class: logging.FileHandler
    # level: TRACE
    # level: DEBUG
    level: INFO
    formatter: formatter_file
    filename: logs/juniper_canopy.log
    mode: w
loggers:
  juniper:
    # level: DEBUG
    level: INFO
    propagate: true
    handlers: [handler_console, handler_file]
root:
  handlers: [handler_console, handler_file]
  # level: TRACE
  # level: DEBUG
  level: INFO
