---
#####################################################################################################################################################################################################
# Project:       Juniper
# Sub-Project:   JuniperCascor
# Application:   juniper_cascor
# Purpose:       Cascade Correlation Neural Network

# Author:        Paul Calnon
# Version:       0.1.4 (0.7.3)
# File Name:     logging_config.yaml
# File Path:     <Project>/<Sub-Project>/<Application>/conf/
#
# Date Created:  2025-10-11
# Last Modified: 2026-01-12
#
# License:       MIT License
# Copyright:     Copyright (c) 2024,2025,2026 Paul Calnon
#
# Description:
#    This file contains the configuration settings for the Juniper prototype
#    Cascade Correlation Neural Network application logging.
#
#####################################################################################################################################################################################################
# Notes:
#
#   Juniper Cascor Application Configuration
#   This file contains all configuration parameters for the CasCor
#   frontend application
#
#####################################################################################################################################################################################################
# References:
#
#####################################################################################################################################################################################################
# TODO :
#
#####################################################################################################################################################################################################
# COMPLETED:
#
#####################################################################################################################################################################################################

version: 1
formatters:
  formatter_console:
    format: "[%(filename)s:%(lineno)d] (%(asctime)s) [%(levelname)s] %(message)s"
    datefmt: "%y-%m-%d %H:%M:%S"
  formatter_file:
    format: "[%(filename)s: %(funcName)s:%(lineno)d] (%(asctime)s) [%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  handler_console:
    class: logging.StreamHandler
    level: INFO
    formatter: formatter_console
    stream: ext://sys.stdout
  handler_file:
    class: logging.FileHandler
    level: INFO
    formatter: formatter_file
    filename: logs/juniper_cascor.log
    mode: w
loggers:
  juniper:
    level: INFO
    propagate: true
    handlers: [handler_console, handler_file]
root:
  handlers: [handler_console, handler_file]
  level: INFO
